### ISSUE TITLE
'list uncompleted' is a redundant command

### ISSUE THREAD

**Issue by yamgent** [CS2103AUG2016-W11-C4/main#138]

**Comment by initialshl** [comment]
Intended behavior?
"Uncompleted" parameter is still required, e.g.
"list uncompleted tasks" is required as "list tasks" will show all uncompleted and completed tasks.

Indeed "list uncompleted" has same behavior as "list", 
but no error other than the user typing more.

**Comment by yamgent** [comment]
I understand what you mean. I think the TA made this comment because of what he saw in the user guide.

I have since revamped the user guide w.r.t the CS2101 feedback (haven't merge yet at time of writing), so I don't think this should be an issue anymore.
