### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2016-W11-C4/main#169]
## User Stories
- User story for `undo` is missing
- Some of the user stories seem duplicate 
- Can reword the user story for update.
## Use cases

Please note that use cases should indicate a user-system interaction; in general it should be to and fro. 
The first use case violates this
## NFR
- Point 1 and 7 are contradictory :-P
- Point 9, you have 3 types of tasks to be supported, no? not just 2
- 13 and 15 seem more functional than NFR.
## Product surveys
- may be make a point to say how you plan to address some of the issues found in the surveyed products?

**Comment by yamgent** [comment]
Thanks for your comments! We will be looking at it soon.

**Comment by yamgent** [comment]
NB: Some of the problems were discovered in cs2101 and fixed. Additional commits 9d9947d, b0bfd64, 9b15463, 173447a added to further fix the problems found in this issue.
