### ISSUE TITLE
Collapse does not work again if 'select' was used on a collapsed list

### ISSUE THREAD

**Issue by yamgent** [CS2103AUG2016-W11-C4/main#232]
```
collapse
select 1
collapse <-- this collapse does not work even though the first task is selected.
```

**Comment by Cherlynn** [comment]
Collapse does not collapse the selected task. The other tasks should be already collapsed though, so the collapse command does not work.

Or do you mean that doing collapse twice should also collapse the selected task?

**Comment by yamgent** [comment]
Ideally yes, but I am going to lower the priority for this right now because there seems to be more bugs for the collapse and expand right now... (#264, #265)

**Comment by yamgent** [comment]
Now I think of it... the design actually make sense. Closing.
