### ISSUE TITLE
Cannot execute 'expand', even though list is collapsed after the app launches

### ISSUE THREAD

**Issue by yamgent** [CS2103AUG2016-W11-C4/main#253]
It will say that the list is already expanded, even though that is clearly not the case.

**Comment by Cherlynn** [comment]
Ok that's strange. Not supposed to be collapsed at launch. Do you know how to reproduce this bug? I can't seem to get the app to do this.

**Comment by Cherlynn** [comment]
Oh nevermind I get it. It was changed to collapse at app launch, but I was on a version before that.
