### ISSUE TITLE
Select command when collapsed not positioned correctly

### ISSUE THREAD

**Issue by initialshl** [CS2103AUG2016-W11-C4/main#264]
With a list of 50+ tasks, run TaSc, type `select 1`, type `select 25` (repeat if necessary).

Task 25 is likely to be wrongly positioned.

<img src="https://cloud.githubusercontent.com/assets/19281538/19830339/73864ef4-9e28-11e6-9ef5-894ec2821529.PNG" width="400">

**Comment by yamgent** [comment]
I relooked at #278, and while it was stated as a partial fix, I don't think the issue will likely re-emerge even though the solution was a bit "hack-ish", as it makes sense that forcing it to scroll again (after Javafx getting it wrong for the first time) should make it work.
