### ISSUE TITLE
Add command did not implement `repeatdeadline` keyword

### ISSUE THREAD

**Issue by initialshl** [CS2103AUG2016-W11-C4/main#96]
Command:
add "developer" by 02/03/2017 14:20:05 repeatdeadline daily 3

Expected result:
added new task with deadline and recurrence

Actual result:
Console log: "INFO: Result: Multiple dates found"
Task is not added

**Comment by yamgent** [comment]
@initialshl Seems like `repeatdeadline` was not implemented by the add command. Did you face the same problem when using `repeattime`?

**Comment by initialshl** [comment]
I see, repeattime works

**Comment by yamgent** [comment]
Okay I will rename this issue to reflect that `repeatdeadline` was not implemented.

**Comment by yamgent** [comment]
@initialshl Btw you can use the `update` command if you need to test something with `repeatdeadline`.

**Comment by yamgent** [comment]
As discussed, we will only have one unified keyword `repeat`.
